# Generated by Django 3.2.4 on 2021-08-13 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
